# Generated by Django 4.0 on 2023-09-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='politician',
            name='picture',
            field=models.ImageField(null=True, upload_to='politicians/'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(default=None, null=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenosapp.charge')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenosapp.party')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenosapp.politician')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenosapp.town')),
            ],
        ),
    ]
