# Generated by Django 4.0 on 2023-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0002_charge_politician_picture_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
