# Generated by Django 4.0 on 2023-09-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0004_alter_job_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start',
            field=models.DateField(),
        ),
    ]
