# Generated by Django 4.0 on 2023-09-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0005_alter_job_end_alter_job_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
