# Generated by Django 4.0 on 2023-09-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0006_alter_job_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='picture',
            field=models.ImageField(null=True, upload_to='politicians/', verbose_name='Foto cuadrada'),
        ),
    ]
