# Generated by Django 4.0 on 2023-09-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0007_politician_url_alter_politician_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('url', models.URLField()),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenosapp.town')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenosapp.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField(null=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenosapp.politician')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenosapp.voting')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plenosapp.meeting')),
                ('voting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plenosapp.voting')),
            ],
        ),
    ]
