# Generated by Django 4.0 on 2023-09-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0008_meeting_voting_vote_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='maxVotes',
            field=models.IntegerField(default=13, verbose_name='Numero de concejales'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.URLField(verbose_name="Youtube url conteniendo 'v='"),
        ),
    ]
