# Generated by Django 4.0 on 2023-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0009_voting_maxvotes_alter_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='videoUrl',
            field=models.URLField(null=True, verbose_name='Url del video en el momento de la votacion'),
        ),
    ]
