# Generated by Django 4.0 on 2023-09-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0010_voting_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='rec1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.URLField(verbose_name="Youtube video url conteniendo 'v='"),
        ),
        migrations.AlterField(
            model_name='voting',
            name='maxVotes',
            field=models.IntegerField(default=13, verbose_name='Número de concejales'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='videoUrl',
            field=models.URLField(null=True, verbose_name='Youtube video url (conteniendo v=) en el momento de la votacion'),
        ),
    ]
