# Generated by Django 4.0 on 2023-09-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plenosapp', '0012_alter_resource_file_alter_resource_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='politician',
        ),
        migrations.AddField(
            model_name='vote',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plenosapp.job'),
            preserve_default=False,
        ),
    ]
